version: "2"

linters:
  default: all
  disable:
    - depguard
    - dupl
    - exhaustive
    - exhaustruct
    - inamedparam
    - ireturn
    - paralleltest
    - recvcheck
    - tagliatelle
    - testpackage
    - unqueryvet
    - wsl
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
    wrapcheck:
      ignore-package-globs:
        # These errors are wrapped already, just passing through the error chain.
        - github.com/opoccomaxao/warera-proxy/pkg/*
        - github.com/pkg/errors
        - errors
    varnamelen:
      ignore-names:
        - wg
        - id
        - i
        - ok
      max-distance: 20
    funcorder:
      constructor: true
      struct-method: false
    gosec:
      excludes:
        - G117
        - G704
    unused:
      exported-fields-are-used: false
      field-writes-are-uses: false
    forbidigo:
      exclude-godoc-examples: true
      analyze-types: true
      forbid:
        - msg: "Use strconv, string concatenation or builder"
          pattern: fmt\.(Sp|P)rintf

  exclusions:
    paths:
      - .local/
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: .*_test\.go
        linters:
          - dupl
          - funlen
          - varnamelen
      - source: MakePackage\(|Serve\(|Descriptions\(|Commands\(|Register\(
        linters:
          - funlen
          - cyclop
      - path: pkg/models
        linters:
          - gochecknoglobals
      - path: pkg/api/
        linters:
          - varnamelen
        text: "parameter name 'w' is too short"

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  new: false
  fix: true

run:
  timeout: 5m
  allow-parallel-runners: true
  concurrency: 10
